### ISSUE TITLE
Support for alternate URLs / domain migration

### ISSUE THREAD

**Issue by bcole808** [bcole808/wp-social-metrics-tracker#45]
# Overview

The plugin currently checks for stats on the live URL to each post. When migrating a site between domains or protocols, old data will be lost because social networks do not transfer share counts between old and new URLs. 

Use cases include [switching a site from http:// to https://](https://wordpress.org/support/topic/url-change-9?replies=1#post-6414612), or migrating between domains. 
## Proposed solution

The plugin will need to know about old/alternate URLs, fetch the data for those URLs, and then add it to the total count for the current URL. 
## Concerns

With each additional check, we are increasing the number of network requests the plugin must make. If migrating a site with 5,000 posts, we might double the requests from 5,000 to 10,000. 

To address this, we can have a separate TTL for old/alternate URLs which is slower (1 week, 1 month, or 6 months, for example), or we can fetch the data only one time for old URLs and never again. 
## Admin UI

There will need to be a settings page which lets admins add old/alternate URLs in bulk when migrating a site between domains. 

For example, an admin could go to this page and tell the plugin that it should also track all http:// versions of the URL, or versions of a URL on a different domain name. 

That page should also allow for all old/alternate URL data to be deleted. 
## Future considerations

In the future, this could be enhanced to automatically detect multiple URLs for a single post (for example if traffic is going to both http:// and https:// versions of the page), or it could watch for changes in the permalink for given posts that already have data for the old permalink. 
# Implementation Details

Here is how this can all work technically:
## Data storage

Information about old/alternate URL share data can be stored in post meta fields as a serialized array; the meta field name will be `socialcount_alt_data`. There can be multiple meta fields with this key and the plugin will just iterate over them (in other words, there can be many old/alternate URLs for a given post). 

``` js
{
    socialcount_alt_data : {
        permalink: 'http://....',
        socialcount_TOTAL : 25,
        socialcount_facebook : 15
        socialcount_twitter : 10
        socialcount_LAST_UPDATED : 1147598437548,
        rule_hash : '....' // if this corresponds to a rewrite rule
    },
    socialcount_alt_data : 'http://....',
}
```

To add an old/alternate URL, a new meta key should be added for `socialcount_alt_data` with the old/alternate URL to track. The presence of a string (URL) in the field means that an update has yet to take place. The presence of an object means that the update has already taken place and data is being factored in to the totals. 
### 1. SSL

There will be a toggle to track both SSL and non-SSL URLs
### 2. Domain Migration

A set of domain rules can be created in the options which will get applied to every post. These rules are intended only for domain migration.  Rules will be stored in the following way:

``` js

alt_url_rules : [
    {
        'rewrite_from' : 'old.domain.com',
        'rewrite_to' : 'newdomain.edu',
        'only_if_before' : '2015-04-26', // optional
        'only_if_after' : '2012-1-30', // optional
        'rule_hash' : '.......' // used to check if a rule has been applied
    },
    ...
]

```
## Task List

**Options**
- [x] Add field for TTL of old/alternate URL data

**MetricsUpdater.class**
- [x] Check for the presence of the meta fields 'socialcount_alt_data'
- [x]   - Validate: strings are proper URLs
- [x]   - Validate: Multiple URLs should return different share counts; if they are always the same, the social network must be counting together and we should not add both. 
- [x]      - Delete entries which fail validation
- [x] Include historical data in totals. 
- [x]  Obey TTL and only update alt_urls one third of the time
- [x] Check and apply Domain Rules to all post URLs
- [x]      If http:// or https:// add one and forcibly remove the other. 

_Keep in mind: When using the same meta key to store multiple values, WP requires that the old value be provided when updating the meta pair._

**Settings Dashboard**
- [x] Add a "Domain Wizard" to create rules that will be applied to post URLs
- [x]   - Domain rule is basically a string replace rule with an optional before/after date specified
- [ ] Add the ability to delete all historical data (remove all past data meta keys)
- [x]   - Page includes FAQ with instructions on how to use. 
- [x]      - FAQ mentions that a unique URL can be added to a single post by adding a custom meta field. 
- [x] Option to default to https:// or http:// protocol (auto-detect the initial setting on plugin activation)

**PHPUnit Tests**
- [x] Update tests for MetricsUpdater.class
- [x] Ensure stats are computed correctly, with `0, 1, 2.... n` number of old/alt URLs
- [ ] Test site migration wizard adds proper meta fields
- [x] Test removal of old/alt data works
- [x] Ensure validation works for URLs

Optional item: Can queries for multiple URLs be combined into one HTTP request? Example:

`https://graph.facebook.com/fql?q=SELECT%20url,%20share_count,%20like_count,%20comment_count,%20total_count,%20click_count%20FROM%20link_stat%20where%20url%20in(%27=http://en.wikipedia.org/wiki/%27,%27=http://en.wikipedia.org/wiki/Main_Page%27,%27=https://en.wikipedia.org/wiki/%27,%27=https://en.wikipedia.org/wiki/Main_Page%27)`
